spring:
  application:
    name: mercado-ganadero-backend
    
  # Database Configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:mercado_ganadero_db}
    username: ${POSTGRES_USER:devuser}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      
  # JPA/Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        default_schema: public
        
  # File Upload Configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:10MB}
      file-size-threshold: 2MB
      
  # Jackson JSON Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
    time-zone: America/Mexico_City

# Server Configuration
server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    
# Application Specific Configuration
app:
  jwt:
    # Tiempo de expiración del ACCESS TOKEN (15 minutos = 900000ms)
    expiration-ms: ${JWT_EXPIRATION_MS:900000}  # 15min

    # Tiempo de expiración del REFRESH TOKEN (7 días)
    refresh-expiration-days: ${JWT_REFRESH_EXPIRATION_DAYS:7}

    # Máximo de sesiones activas por usuario
    max-active-sessions: ${JWT_MAX_ACTIVE_SESSIONS:5}

    # Emisor del token (para validación)
    issuer: ${JWT_ISSUER:mercado-ganadero}

    file:
      upload-dir: ${FILE_UPLOAD_DIR:./uploads}

    cors:
      allowed-origins: http://localhost:3000,http://localhost:4200,http://localhost:5173
    
# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
      
# Logging Configuration
logging:
  level:
    root: INFO
    com.mercadoganadero: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE:./logs/application.log}
    max-size: 10MB
    max-history: 30